---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage

- type: document
  path: exampleSite/data/en/homepage.yml
  label: Homepage (en)

- type: heading
  label: People
- type: directory
  path: exampleSite/content/english/people
  label: People
  create: documents
  match: "**/*"
  templates:
  - person

- type: heading
  label: Publications
- type: directory
  path: exampleSite/content/english/publications
  label: Publications
  create: documents
  match: "**/*"
  new_doc_ext: '20191203072044'
  templates:
  - post

- type: heading
  label: Events
- type: directory
  path: exampleSite/content/english/events
  label: Events
  create: documents
  match: "**/*"
  new_doc_ext: '20191203072044'
  templates:
  - post

- type: heading
  label: News
- type: directory
  path: exampleSite/content/english/news
  label: News
  create: documents
  match: "**/*"
  new_doc_ext: '20191203072044'
  templates:
  - post


- type: heading
  label: Facilities
- type: directory
  path: exampleSite/content/english/facilities
  label: Facilities
  create: documents
  match: "**/*"
  new_doc_ext: '20191203072044'
  templates:
  - post

- type: heading
  label: Opportunities
- type: directory
  path: exampleSite/content/english/opportunities
  label: Opportunities
  create: documents
  match: "**/*"
  new_doc_ext: '20191203072044'
  templates:
  - post

- type: heading
  label: Contact
- type: document
  path: exampleSite/content/english/contact/_index.md
  label: Contact (en)

- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content/english
  label: All Page (en)
  create: all
  match: "**/*"

buttons:
- name: All
  filter: "all"
- name: Hacking
  filter: "hacking"
- name: Computers
  filter: "computers"
- name: Software
  filter: "software"

- type: heading
  label: Configuration
- type: document
  path: exampleSite/config.toml
  label: Configuration
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
